---
title: "Kickoff "
author: "Peter Ganong and Maggie Shi"
date: October 23, 2024
date-format: long
format: 
    beamer:
        aspectratio: 169
        theme: default
        header-includes: \renewcommand{\tightlist}{\setlength{\itemsep}{3ex}\setlength{\parskip}{0pt}}
            \setbeamertemplate{footline}[frame number]
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
---

## Misc MUD + Admin
* Github classroom teams is broken at the moment. See Canvas for our PS3 workaround. Hope to have it fixed for remaining problem sets.
* What is a good set of reference material to use after class? Textbooks!
* What are expectations for calendar/time allocation?
    * Weekly PS until Thanksgiving (last one due 11/16)
    * Final project akin to an extended, less structured PS (present in class 12/2-12/5)
    * Study for final (12/12)

## git
- “I still have no clue why we are learning git”
- How do I handle merge conflicts?
- Show the command line. Change directory, list files (`ls` or `dir`). git status, git commit, and git log.
- Tech setup
    - By now, you should have command line git installed 
    - If you want to get ahead for the do-pair-share, fork https://github.com/uchicago-harris-dap/merge_example on github.com and then clone the repo to your computer


## Final Project meetings

Send questions in advance in Ed via tag "Final project ganong"

First come first serve sign up **[here](https://docs.google.com/spreadsheets/d/1C696XfJpfB7Wz0ncMOjq2l10PUnBSZ5jBfZWawF36tg/edit?gid=0#gid=0)**. Meet in room 0049.

