---
title: "Kickoff "
author: "Peter Ganong and Maggie Shi"
date: October 30, 2024
date-format: long
format: 
    beamer:
        aspectratio: 169
        theme: default
        header-includes: \renewcommand{\tightlist}{\setlength{\itemsep}{3ex}\setlength{\parskip}{0pt}}
            \setbeamertemplate{footline}[frame number]
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
---


## MUD Final project

* Timeline
    * Idea/plan/partners -- now
    * Work one week in Nov before Thanksgiving
    * Mon-Tue-Wed before Thanksgiving
    * you might have time after break depending on your slot (slots allocated randomly, will post schedule after the quiz due Friday closes).
* Where to find datasets 
    * Choose one connected to your policy interests. 
    * It will be better for your job applications / portfolio if you choose the dataset, not me. 
    * Public datasets are everywhere: Google cloud, Kaggle, city's open data portals, replication files for academic papers


## PS3 debrief

* Overall students did very well, not a lot of systematic or correlated errors.
* Some students wrote answers and did not present any git output, we marked them down since we could not verify their answers

## PS4 small changes I

We updated the problem set in the student repo.

* In "Calculate zip code’s distance to the nearest hospital", we simplified 2. You no longer have to create a function to see if the polygons intersect.
* In "Calculate zip code’s distance to the nearest hospital", we eliminated 4a. You no longer have to time the join of the subset first.

## PS4 small changes II

* Mitch noted that there was a discrepancy in the template (which had subquestions) and the problem set (which in the student repo did not). Thank you!
    * The problem set has been updated
* The template was missing some of the header material
    * This issue is fixed (but not need ) 
    * Going forward, we will put header material in exactly one place, which will be the template
